import type { Metadata } from "next";
import { nikkeimaru } from "../fonts/fonts";
import "./globals.css";

import Cursor from "../components/global/effects/Cursor";
import SmoothScroll from "../components/global/effects/SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nikkeimaru.className} antialiased`}>
        <SmoothScroll>
          <Cursor />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
